apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: dev
    tie: front
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
