apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: petclinic
  labels:
    app: petclinic
    version: v1.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      version: v1.0.1
      color: blue
  template:
    metadata:
      labels:
        app: petclinic
        version: v1.0.1
        color: blue
    spec:
      containers:
        - name: petclinic
          image: spring2go/spring-petclinic:1.0.0.RELEASE
