apiVersion: v1
kind: Pod
metadata:
  name: petclinic-v1.0.0
  labels:
    app: petclinic
    version: v1.0.0
spec:
  containers:
    - name: petclinic
      image: spring2go/spring-petclinic:1.0.0.RELEASE
