apiVersion: v1
kind: Pod
metadata:
  name: petclinic-v1.0.1
  labels:
    app: petclinic
    version: v1.0.1
spec:
  containers:
    - name: petclinic
      image: spring2go/spring-petclinic:1.0.1.RELEASE
